apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-17
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  enableSuperuserAccess: true

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      import:
        type: microservice
        databases:
          - postgres
        source:
          externalCluster: cluster-example

  externalClusters:
    - name: cluster-example
      connectionParameters:
        # Use the correct IP or host name for the source database
        host: cluster-example-rw
        user: postgres
        dbname: postgres
      password:
        name: cluster-example-superuser
        key: password

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "512Mi"
      cpu: "1"
