apiVersion: v1
data:
  password: dU4zaTFIaDBiWWJDYzRUeVZBYWNCaG1TemdxdHpxeG1PVmpBbjBRSUNoc0pyU211OVBZMmZ3MnE4RUtLTHBaOQ==
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: cluster-example-superuser
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  enableSuperuserAccess: true

  # Reduce the frequency of standby HA slots updates to once every 5 minutes
  replicationSlots:
    highAvailability:
      enabled: true
    #updateInterval: 300

  postgresql:

    synchronous:
      method: any
      number: 1
      # preferred: Focuses on self-healing and high availability by automatically 
      # disabling synchronous replication when no replicas are available in the cluster.
      dataDurability: preferred

    parameters:
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
    pg_hba:
      - host replication all all trust
      - hostssl replication all all trust
      - hostssl replication streaming_replica all cert
      - host all all 0.0.0.0/0 md5

  storage:
    size: 1Gi
  walStorage:
    size: 1Gi
  tablespaces:
  - name: idx
    storage:
      size: 1Gi
  - name: tmptbs
    temporary: true
    storage:
      size: 1Gi

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: "512Mi"
      cpu: "0.4"
    limits:
      memory: "1Gi"
      cpu: "0.4"

  #affinity:
  #  nodeSelector:
  #    workload: dc1

