apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-restore
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  #imagePullPolicy: Never

  storage:
    size: 1Gi
  walStorage:
    size: 1Gi
  tablespaces:
  - name: idx
    storage:
      size: 1Gi
  - name: tmptbs
    temporary: true
    storage:
      size: 1Gi

  monitoring:
    enablePodMonitor: true

  bootstrap:
    recovery:
      backup:
        name: backup-test
