apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example2
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1


  storage:
    size: 500Mi
  resources:
    requests:
      memory: "1Gi"
      cpu: "0.3"
    limits:
      memory: "1Gi"
      cpu: "0.3"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: datacenter
                operator: In
                values:
                  - dc2
